version: 2
updates:

  - package-ecosystem: npm
    directory: '/'
    schedule:
        interval: monthly

    groups:
      opentelemetry:
        patterns:
        - '@opentelemetry/*'
      dev-deps:
        dependency-type: development

    ignore:
    # Stay on React 18 until
    - dependency-name: 'react'
      versions:
      - '>= 19'
    - dependency-name: '@types/react'
      versions:
      - '>= 19'
    - dependency-name: 'react-dom'
      versions:
      - '>= 19'
    - dependency-name: '@types/react-dom'
      versions:
      - '>= 19'

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
