---
apiVersion: bundle.dist.app/v1alpha1
kind: DocumentCollection
metadata:
  name: Wheels
spec:
  apiVersion: task-spinner.dist.app/v1alpha1
  items:
    kind: Wheel
    plural: wheels
    singular: wheel
    openAPIV3Schema:
      type: object
      required:
      - spec
      properties:
        spec:
          type: object
          required:
          - createdAt
          - label
          properties:
            createdAt:
              type: dateTime
            label:
              type: string

---
apiVersion: bundle.dist.app/v1alpha1
kind: DocumentCollection
metadata:
  name: Wedges
spec:
  apiVersion: task-spinner.dist.app/v1alpha1
  items:
    kind: Wedge
    plural: wedges
    singular: wedge
    openAPIV3Schema:
      type: object
      required:
      - spec
      properties:
        spec:
          type: object
          required:
          - createdAt
          - label
          - wheelId
          - createdAt
          - lifecycle
          - label
          - weight
          - color
          properties:
            wheelId:
              type: string
            createdAt:
              type: dateTime
            drawnAt:
              type: dateTime
            doneAt:
              type: dateTime
            lifecycle:
              type: string
              enum:
              - live
              - icebox
              - drawn
              - done
              - dropped
            label:
              type: string
            weight:
              type: number
              # TODO: integer
              # TODO: min 1
            color:
              type: string
