---
apiVersion: bundle.dist.app/v1alpha1
kind: AppManifest
metadata:
  name: task-wheel
spec:
  title: Task Wheel
  description: Spinner for the todos that you aren't excited about
  iconRef:
    apiVersion: manifest.dist.app/v1alpha1
    kind: GlyphIcon
    name: primary
    # spec:
    #   text: 🤸🏻
    #   backgroundColor: '#d9941e'

---
apiVersion: manifest.dist.app/v1alpha1
kind: GlyphIcon
metadata:
  name: primary
spec:
  text: 🤸🏻
  backgroundColor: '#d9941e'

---
apiVersion: bundle.dist.app/v1alpha1
kind: MeteorBundle
metadata:
  name: client
spec:
  sourcePath: .
  platforms:
  - web.browser

---
apiVersion: bundle.dist.app/v1alpha1
kind: DdpBackend
metadata:
  name: server
spec:
  meteorBundleName: client
  spaPathPatterns:
  - /
  - /wheels/*
  authnMethods:
    oidc:
      issuer: https://login.dist.app
    cookie:
      sessionLengthDays: 14
  storageMode: IsolationByIdentity
