---
apiVersion: schema.dist.app/v1alpha1
kind: EntityKind
metadata:
  name: wheels.task-spinner.dist.app
  labels:
    ddp.dist.app/collection-name: Wheels
spec:
  group: task-spinner.dist.app
  names:
    kind: Wheel
    plural: wheels
    singular: wheel
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        required:
        - spec
        properties:
          spec:
            type: object
            required:
            - createdAt
            - label
            properties:
              createdAt:
                type: dateTime
              label:
                type: string

---
apiVersion: schema.dist.app/v1alpha1
kind: EntityKind
metadata:
  name: wedges.task-spinner.dist.app
  labels:
    ddp.dist.app/collection-name: Wedges
spec:
  group: task-spinner.dist.app
  names:
    kind: Wedge
    plural: wedges
    singular: wedge
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        required:
        - spec
        properties:
          spec:
            type: object
            required:
            - createdAt
            - label
            - wheelId
            - createdAt
            - lifecycle
            - label
            - weight
            - color
            properties:
              wheelId:
                type: string
              createdAt:
                type: dateTime
              drawnAt:
                type: dateTime
              doneAt:
                type: dateTime
              lifecycle:
                type: string
                enum:
                - live
                - icebox
                - drawn
                - done
                - dropped
              label:
                type: string
              weight:
                type: number
                # TODO: integer
                # TODO: min 1
              color:
                type: string
